version: "3.9"

services:

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: restaurant-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: